> edd:cdd("tcp:main()", 4000).                      
Instrumenting..."tcp.erl"

Tracing timeout

**********************************
PROCESS <12327.76.0>
First call tcp:client_fun(<12327.74.0>, 50, 200, client2)
Result Blocked because it is waiting for a message
Sent messages:
        {<12327.76.0>,{syn,50,200}} (from <12327.76.0> to <12327.74.0>)
No spawned processes
**********************************

**********************************
PROCESS <12327.75.0>
First call tcp:client_fun(<12327.74.0>, 57, 100, client1)
Result {port_rejected,57}
Sent messages:
        {<12327.75.0>,{syn,57,100}} (from <12327.75.0> to <12327.74.0>)
No spawned processes
**********************************

**********************************
PROCESS <12327.74.0>
First call tcp:server_fun(<12327.72.0>, 50, 500)
Result rst
Sent messages:
        rst (from <12327.74.0> to <12327.75.0>)
No spawned processes
**********************************

**********************************
PROCESS <12327.72.0>
First call tcp:main()
Result Blocked because it is waiting for a message
No sent messages
Spawned processes:
        <12327.76.0>
        <12327.75.0>
        <12327.74.0>
**********************************

**********************************
Pid selection
**********************************
1.- <12327.76.0>
        First call: tcp:client_fun(<12327.74.0>, 50, 200, client2)
        Result: Blocked because it is waiting for a message
2.- <12327.75.0>
        First call: tcp:client_fun(<12327.74.0>, 57, 100, client1)
        Result: {port_rejected,57}
3.- <12327.74.0>
        First call: tcp:server_fun(<12327.72.0>, 50, 500) 
        Result: rst
4.- <12327.72.0>
        First call: tcp:main()
        Result: Blocked because it is waiting for a message
5.- Choose an event
6.- None

Please, insert a PID where you have observed a wrong behavior (or 5 to select an event): [1..6]: 3

Selected initial PID: <12327.74.0>
        First call: tcp:server_fun(<12327.72.0>, 50, 500)
        Result: rst

**********************************

**********************************
Process <12327.74.0> called tcp:server_fun(<12327.72.0>, 50, 500).
What is wrong?
1. - Previous evaluated receive:
        receive
          {Client_PID, {syn, Port, SeqCl}} ->
              Ack_PID = spawn(tcp, ack,
                              [Main_PID, Port, SeqCl + 1, Seq + 1, Client_PID]),
              Client_PID ! {Ack_PID, {syn_ack, SeqCl + 1, Seq}},
              server_fun(Main_PID, Port, Seq + 1);
          {Client_PID, {syn, _, _}} -> Client_PID ! rst
        end
        in tcp.erl:13
        Context:
                'Client_PID' = <12327.75.0>
                'Main_PID' = <12327.72.0>
                'Port' = 50
                'Seq' = 500
        Received messages:
                {<12327.75.0>,{syn,57,100}} (from <12327.75.0> to <12327.74.0>)
                {<12327.76.0>,{syn,50,200}} (from <12327.76.0> to <12327.74.0>)
        Consumed messages:
                {<12327.75.0>,{syn,57,100}} (from <12327.75.0> to <12327.74.0>)
2. - Evaluated to value: rst
3. - Sent messages:
        rst (from <12327.74.0> to <12327.75.0>)
4. - No created processes
5. - Nothing
[1/2/3/4/5/t/d/i/c/s/p/r/u/h/a]: 2

**********************************
Process <12327.74.0> evaluated
receive
  {Client_PID, {syn, Port, SeqCl}} ->
      Ack_PID = spawn(tcp, ack,
                      [Main_PID, Port, SeqCl + 1, Seq + 1, Client_PID]),
      Client_PID ! {Ack_PID, {syn_ack, SeqCl + 1, Seq}},
      server_fun(Main_PID, Port, Seq + 1);
  {Client_PID, {syn, _, _}} -> Client_PID ! rst
end
in tcp.erl:13
What is wrong?
1. - Context:
        'Client_PID' = <12327.75.0>
        'Main_PID' = <12327.72.0>
        'Port' = 50
        'Seq' = 500
2. - Received messages:
        {<12327.75.0>,{syn,57,100}} (from <12327.75.0> to <12327.74.0>)
        {<12327.76.0>,{syn,50,200}} (from <12327.76.0> to <12327.74.0>)
3. - Consumed messages:
        {<12327.75.0>,{syn,57,100}} (from <12327.75.0> to <12327.74.0>)
4. - Evaluated to value: rst
5. - Sent messages:
        rst (from <12327.74.0> to <12327.75.0>)
6. - No created processes
7. - Nothing
[1/2/3/4/5/6/7/t/d/i/c/s/p/r/u/h/a]: 4

The error has been detected:
The problem is in pid <12327.74.0>
while running receive
receive
  {Client_PID, {syn, Port, SeqCl}} ->
      Ack_PID = spawn(tcp, ack,
                      [Main_PID, Port, SeqCl + 1, Seq + 1, Client_PID]),
      Client_PID ! {Ack_PID, {syn_ack, SeqCl + 1, Seq}},
      server_fun(Main_PID, Port, Seq + 1);
  {Client_PID, {syn, _, _}} -> Client_PID ! rst
end
in tcp.erl:13

